#!/bin/sh

rm -f csh-out shell-out
echo "Test15: Enviroment: Variable expansion"
echo "setenv A hello" > shell-in
echo "setenv B world" >> shell-in
echo "echo \${A} \${B}" >> shell-in
echo "A=hello" > csh-in
echo "B=world" >> csh-in
echo "echo \${A} \${B}" >> csh-in

/bin/sh < csh-in > csh-out 2>&1
../shell < shell-in > shell-out

diff shell-out csh-out
if [ $? -ne 0 ]
then
    echo "Test15 failed"
    exit -1
fi
echo Test15 OK
exit 0
