#!/bin/sh

rm -f csh-out shell-out
echo "Test111: cd; echo *"
echo "cd" > shell-in
echo "echo *" >> shell-in
echo "echo .*" >> shell-in

echo "cd" >  csh-in
echo "echo *" >> csh-in
echo "echo .*" >> csh-in

/bin/sh < csh-in > csh-out 2>&1
../shell < shell-in > shell-out 2>&1

diff shell-out csh-out
if [ $? -ne 0 ]
then
    echo "Test111 failed"
    exit -1
fi
echo Test111 OK
exit 0
