#!/bin/sh

rm -f csh-out shell-out
echo "Test108: echo /usr/lib/*"
echo "echo /usr/lib/*" > shell-in
echo "echo /usr/lib/*" > csh-in

/bin/sh < csh-in > csh-out 2>&1
../shell < shell-in > shell-out 2>&1

diff shell-out csh-out
if [ $? -ne 0 ]
then
    echo "Test108 failed"
    exit -1
fi
echo Test108 OK
exit 0
