#!/bin/sh
rm -f err1 err2 out1 out2 csh-out shell-out
echo "Test3: Appending output"
echo "ls files > out1" > shell-in
echo "ls files > out1" >> shell-in
echo "ls files >> out1" >> shell-in
echo "ls files > out2" > csh-in
echo "ls files > out2" >> csh-in
echo "ls files >> out2" >> csh-in

/bin/sh < csh-in > csh-out
../shell < shell-in > shell-out

diff out1 out2
if [ $? -ne 0 ]
then
    echo "Test3-2 failed"
    exit -1
fi
echo Test3-2 OK
exit 0
