#!/bin/sh

rm -f csh-out shell-out
echo "Test114: ls \"command.cc Makefile\""
echo "ls file1.cc files" > shell-in
echo "ls \"file1.cc files\"" >> shell-in

echo "ls file1.cc files" >  csh-in
echo "ls \"file1.cc files\"" >> csh-in

/bin/sh < csh-in > csh-out 2>&1
../shell < shell-in > shell-out 2>&1

diff shell-out csh-out
if [ $? -ne 0 ]
then
    echo "Test114 failed"
    exit -1
fi
echo Test114 OK
exit 0
