#!/bin/sh
echo "Test204: test tilde expansion"

echo "ls ~ > out1" > csh-in
echo "ls ~cs180 >> out1" >> csh-in
echo "ls ~cs180/share >> out1" >> csh-in

echo "ls ~ > out2" > shell-in
echo "ls ~cs180 >> out2" >> shell-in
echo "ls ~cs180/share >> out2" >> shell-in

/bin/bash < csh-in > csh-out 
../shell < shell-in > shell-out 


diff out1 out2 > /dev/null 2>&1
if [ $? -ne 0 ]
then
    echo "Test204 failed. "
    rm -fr csh-in csh-out shell-in shell-out out1 out2
    exit -1
fi
rm -fr csh-in csh-out shell-in shell-out out1 out2
echo Test204 OK
exit 0

