#!/bin/sh

rm -f csh-out shell-out
echo "Test110: echo /usr/lib/*ck*"
echo "echo /usr/lib/*ck*" > shell-in
echo "echo /usr/lib/*ck*" > csh-in

/bin/sh < csh-in > csh-out 2>&1
../shell < shell-in > shell-out 2>&1

diff shell-out csh-out
if [ $? -ne 0 ]
then
    echo "Test110 failed"
    exit -1
fi
echo Test110 OK
exit 0
