#!/bin/sh

rm -f csh-out shell-out
echo "Test107: echo *"
touch shell-in csh-in shell-out csh-out
echo "echo *" > shell-in
echo "echo *" > csh-in

/bin/sh < csh-in > csh-out 2>&1
../shell < shell-in > shell-out 2>&1

diff shell-out csh-out
if [ $? -ne 0 ]
then
    echo "Test107 failed"
    exit -1
fi
echo Test107 OK
exit 0
