#!/bin/sh

rm -f csh-out shell-out
echo "Test113: cd; echo lll \">\" "
echo "cd" > shell-in
echo "echo lll \">\"" >> shell-in

echo "cd" >  csh-in
echo "echo lll \">\"" >> csh-in

/bin/sh < csh-in > csh-out 2>&1
../shell < shell-in > shell-out 2>&1

diff shell-out csh-out
if [ $? -ne 0 ]
then
    echo "Test113 failed"
    exit -1
fi
echo Test113 OK
exit 0
